simulation:
  seed: 43
  grid_lims: [0, 1]
  sample_sizes: [20000, 100000] #, 5000, 10000, 20000] #, 5000, 10000] #, 10000] #, 5000, 10000]  # Different sample sizes for datasets
  dimensions: [2] # , 5]  # 1D, 2D, or 3D datasets
  likelihoods: 
     - gaussian
   # - t
   # - chi
    # - ald
    #- ald_heteroscedastic # testing heteroscedasticity
  
  # Simulation Settings
  snr: 10.0                # Desired signal-to-noise ratio
  fixed_snr: True          # True = homoscedastic noise with this SNR; False = heteroscedastic
  pars : {
    "gaussian": {"scale": 0.31}, # sqrt(0.31) -> 0.1
    "ald": {"q": 0.8, "scale": 0.1}, #
    "t": {"df": 3, "scale": 0.1},
    "chi": {"df": 2, "scale": 0.1}
  }
  # useless noise_levels: [0.1, 0.2, 0.3]  # Noise levels for adding to data
  replicates: 5

# update also simulation config
gp_parameters:
  kernel:
    type: matern
    nu: 1.5
    lengthscale: 0.05
    signal_variance: 1.0
  # You can add more GP parameters as needed


## TARGET QUANTILE ##
target_quantile: 0.8

# MIN DECREASE LOG-LIKELIHOOD FOR GPBOOST
delta_logl: 10


# specific for the simulation run
threshold_approximation: 1001
inducing_points:  1000

# level for prediction intervals --> build a alphax100% prediction interval
alpha: 0.9

train_split: 0.75

# for python
models: ["gpboost_normal" ] #, "gpboost_cc"] # ["gpboost_cc", "gpboost_lls", "gpboost_fisher", "gpboost_normal"] #["gpboost_cc", "gpboost_cc_var_corr", "VIVA"] #, "qgam"] "gpytorch"
# hyper-params --> useful for producing later results
models_with_hyperparams: ["gpboost_normal"] #, "gpboost_cc"] #["gpboost_cc", "gpboost_lls", "gpboost_fisher", "gpboost_normal"] #"gpboost_cc_var_corr", "gpytorch", "VIVA"]

gpb_approxs: {"gpboost_fisher": "asymmetric_laplace",
           "gpboost_lls": "asymmetric_laplace_lls_laplace_fisher_mode_finding",
            "gpboost_cc": "asymmetric_laplace_constant_curvature_fisher_mode_finding",
            "gpboost_cc_var_corr": "asymmetric_laplace_constant_curvature_fisher_mode_finding_var_cor_pred",
            "gpboost_normal": "gaussian"}



# for GPytorch
n_epochs : 200
lr: 0.01


# fix dicts
name_dict : {"gpboost_lls": "LLS", "gpboost_cc": "CC", "gpytorch": "VI", "qgam":"GAM", "gpboost_normal": "gpbN",
            "gpboost_cc_var_corr": "CC corr", "vecchia_mcmc": "BSGP", "VIVA":"VIVA", "gpboost_fisher":"FL"}
likelihood_dict : {"gaussian":"N", "ald": "ALD", "t":"t", "chi":"chi", "ald_heteroscedastic": HetALD}

# what I want to plot/make latex tables for
all_models: ["gpboost_normal"] #, "gpboost_cc"] # ["gpboost_cc", "gpboost_lls", "gpboost_fisher", "gpboost_normal"] #gpboost_cc_var_corr", "gpytorch", "qgam", "vecchia_mcmc", "VIVA"] # ["gpboost_lls", "gpboost_cc", "gpytorch", "qgam"]



