group_sizes: [100, 200, 500, 1000]
num_groups: 20
re_std: 1.0
scale_laplace: 1.0
quantile: 0.8
min_decrease: 10
laplace_approximations : ["asymmetric_laplace_fisher_mode_finding",
                          "asymmetric_laplace_constant_curvature_fisher_mode_finding", 
                          "asymmetric_laplace_lls_laplace_fisher_mode_finding"]
approx_dict : {"asymmetric_laplace_constant_curvature_fisher_mode_finding": "CC",
               "asymmetric_laplace_lls_laplace_fisher_mode_finding": "LLS", 
               "asymmetric_laplace_fisher_mode_finding":"Fisher-Laplace"}
B: 50
integration_nodes: 100
misspecified: False
use_pred_var : False
estimate_scale : False # does it make sense to estimate the scale parameter in what we want to show?

