target_quantile: 0.8

delta_logl: 0.1
models:  ["gpboost_cc", "gpboost_lls", "gpboost_fisher"] #, "gpb "gpboost_lls_v2"

estimate_hyper: True

gpb_approxs: {"gpboost_fisher": "asymmetric_laplace",
            "gpboost_lls": "asymmetric_laplace_lls_laplace_fisher_mode_finding",
            "gpboost_lls_v2": "asymmetric_laplace_lls_laplace_v2_fisher_mode_finding",
            "gpboost_cc": "asymmetric_laplace_constant_curvature_fisher_mode_finding",
            "gpboost_cc_var_corr": "asymmetric_laplace_constant_curvature_fisher_mode_finding_var_cor_pred",
            "gpboost_normal": "gaussian"}



datasets: ["labor", "Orthodont"] #"Orthodont", "labor"] #, "cars"] #Orthodont", "labor"] #, "labor", "cars"] # ["Orthodont", "labor"] cars_crossed

n_splits: 10


#### ANALYSIS ###
all_models: ["gpboost_cc", "gpboost_fisher", "lqmm", "brms", "bayesqr"]  # also eventually Qgam
name_dict : {"gpboost_lls": "LLS", "gpboost_cc": "CC", "gpboost_cc_var_corr": "CC corr", "brms": "BRMS", "lqmm":"LQMM", "gpboost_normal": "gpbN", 
              "gpboost_fisher": "Fisher", "bayesqr": "BayesQR", "gpboost_lls_v2": "LLSV2"} 
