# Configuration for Thermodynamic Integration and Annealed Importance Sampling Simulation

dimension: 2  # Dimension of the input space (e.g., 1D or 2D grid)
sample_size: 50  # Number of data points

grid_lims: [0, 10]  

# carl setting
num_samples: 1000

quantile: 0.8  # Quantile for Asymmetric Laplace, carefull!!

kernel:
  nu: 1.5  # Smoothness parameter of the Matern kernel
  lengthscale: 1.0  # Lengthscale parameter of the kernel
  signal_variance: 1.0  # Variance of the signal (GP prior)

likelihood: "ald"  # Likelihood type (e.g., "gaussian", "laplace", etc.)
pars : {
    "gaussian": {"scale": 0.5},
    "ald": {"q": 0.8, "scale": 0.1},
    "t": {"df": 3, "scale": 1},
    "chi": {"df": 2, "scale": 1}
  }

scale_laplace: 0.1 ## CAREFULL !!

min_decrease: 10  # Minimum decrease threshold for model fitting

# GPBoost settings (if applicable)
gpboost:
  min_dec: 0.01  # Minimum decrease for GPBoost optimization
  laplace_approximations:
    - "asymmetric_laplace"
    - "asymmetric_laplace_constant_curvature_fisher_mode_finding"
    - "asymmetric_laplace_lls_laplace_fisher_mode_finding"
  names:
    - "Fisher"
    - "CC"
    - "LLS"

