simulation:
  seed: 43
  grid_lims: [0, 1]
  sample_sizes: [1000, 10000] 
  dimensions: [2, 5] 
  likelihoods: 
     - gaussian
     - t
     - gaussian_heteroscedastic
  
  # Simulation Settings
  snr: 5.0                # Desired signal-to-noise ratio
  fixed_snr: True          # True = homoscedastic noise with this SNR; False = heteroscedastic
  pars : {
    "gaussian": {"scale": 0.31}, # sqrt(0.31) -> 0.1
    "ald": {"q": 0.8, "scale": 0.1}, #
    "t": {"df": 3, "scale": 0.1},
    "chi": {"df": 2, "scale": 0.1}
  }
  replicates: 10

# update also simulation config
gp_parameters:
  kernel:
    type: matern
    nu: 1.5
    lengthscale: 0.25
    signal_variance: 1.0
  # You can add more GP parameters as needed

## TARGET QUANTILE ##
target_quantile: 0.80 #0.95

# MIN DECREASE LOG-LIKELIHOOD FOR GPBOOST
delta_logl: 10

# specific for the simulation run
threshold_approximation: 1001
inducing_points:  1000

# level for prediction intervals --> build a alphax100% prediction interval
target_coverage: 0.9

# train-test split
train_split: 0.75

# for python
models: ["gpboost_cc", "gpboost_fisher", "gpytorch", "VIVA"] #[
# hyper-params --> useful for producing later results
models_with_hyperparams:  ["gpboost_cc", "gpboost_fisher", "gpytorch",  "VIVA"] 

gpb_approxs: {"gpboost_fisher": "asymmetric_laplace_fisher_mode_finding", # use continue as well, second order helps if not local!
           "gpboost_lls": "asymmetric_laplace_lls_laplace_fisher_mode_finding",
            "gpboost_cc": "asymmetric_laplace_constant_curvature_fisher_mode_finding",
            "gpboost_cc_var_corr": "asymmetric_laplace_constant_curvature_fisher_mode_finding_var_cor_pred_freq_asym",
            "gpboost_normal": "gaussian",
            "gpboost_lls_v2": "asymmetric_laplace_lls_laplace_v2_fisher_mode_finding",
            "gpboost_groups": "asymmetric_laplace_lls_laplace_groups_fisher_mode_finding",
            "gpboost_cc_cv": "asymmetric_laplace_constant_curvature_constant_fisher_mode_finding",
            "gpboost_fisher_twostage": "asymmetric_laplace_fisher_mode_finding",
            "gpboost_fisher_clip": "asymmetric_laplace_kink_clipping",
            "gpboost_fisher_fi": "asymmetric_laplace_var_cor_pred_freq_asym"}

# for GPytorch
n_epochs : 200
lr: 0.01

# model dictionary for latex tables
name_dict : {"gpboost_lls": "LLS", "gpboost_cc": "TKC", "gpboost_cc_cv": "CC_cv" ,"gpytorch": "VI", "qgam":"QGAM", "gpboost_normal": "gpbN",
            "gpboost_cc_var_corr": "CC corr", "vecchia_mcmc": "BSGP", "VIVA":"VIVA",
             "gpboost_fisher":"FL", "gpboost_lls_v2": "LLSV2", "gpboost_groups": "Groups",
             "gpboost_fisher_twostage": "FL-2stage", "qgam_interactions":"QGAMInt", 
              "gpboost_fisher_clip": "FL-clip", "gpboost_fisher_fi": "FL-FI"}
# likelihood dictionary for latex tables          
likelihood_dict : {"gaussian":"N", "ald": "ALD", "t":"t", "chi":"chi", "ald_heteroscedastic": "HetALD", "gaussian_heteroscedastic": "HetN"}

# what I want to plot/make latex tables for
all_models: ["gpboost_cc", "gpboost_fisher", "gpytorch", "VIVA", "qgam", "qgam_interactions"]