gp_parameters:
  kernel:
    type: matern
    nu: 1.5
    lengthscale: 0.5
    signal_variance: 2.0
 

# specific for the simulation run
## TARGET QUANTILE
target_quantile: 0.8

threshold_approximation: 1001
inducing_points:  1000

delta_logl: 10

# level for prediction intervals --> build a alphax100% prediction interval
alpha: 0.9

n_splits: 5

datasets: ["laegern", "modis", "heaton", "house"] # , "power"] #, "power", "houses", "elevators", "protein"]
models: ["VIVA", "gpboost_fisher", "gpytorch"] #"gpboost_fisher", "gpytorch"] #, "gpboost_lls", "gpytorch"], gpboost_cc
gpb_approxs: {"gpboost_lls": "asymmetric_laplace_constant_curvature_fisher_mode_finding",
            "gpboost_cc": "asymmetric_laplace_constant_curvature_fisher_mode_finding",
            "gpboost_fisher": "asymmetric_laplace_fisher_mode_finding"}


# for GPytorch
n_epochs : 200

lr: 0.01

# for later, plotting
all_models:  ["gpboost_fisher", "gpboost_cc", "gpytorch", "qgam", "qgam_interactions", "VIVA"] # "gpboost_lls", 
name_dict : {"gpboost_lls": "LLS", "gpboost_cc": "CC", "gpytorch": "VI", "qgam":"QGAM","qgam_interactions":"QGAM Int",
  "gpboost_fisher":"FL", "boosting": "Boosting", "VIVA": "VIVA"}
