# General parameters for data generation and splitting
data_generation:
  n_groups: [100] #, 500] # [200,  1000]
  group_size: [10, 100, 500]
  n_groups_2 : 50 # how many levels for the second random effect -->  group_size > n_groups_2 # N/n_group_2, should be an integer
  signal_variance: 1.0 # for one grouped random effect
  signal_variance_2: 2.0 # for second random effect
  
  fixed_snr: True
  snr: 5.0
  quantile: 0.8
  likelihood: ["t", "ald", "gaussian"] # ald, t, gaussian
  pars : {
    "gaussian": {"scale": 0.31}, # sqrt(0.31) -> 0.1
    "ald": {"q": 0.8, "scale": 0.1}, #
    "t": {"df": 3, "scale": 0.1},
    "chi": {"df": 2, "scale": 0.1}
  }
  replicate: 10
  test_size: 0.25
  randeff: "One_random_effect" # "One_random_effect" Two_completely_crossed_random_effects
  output_folder: "simulated_data_mm"
  random_state: 123
  extrapolate: False

  # FIXED EFFECTS
  num_covariates: 5
  has_F: False
  factor_m2: 1.0
  

  # FOR MORE COMPLEX RANDOM EFFECTS STRUCTURES
  sigma2: 0.25 
  sigma2_1: 0.25
  sigma2_2: 0.25
  sigma2_3: 0.25

##### for running simulation ########
models:  ["gpboost_fisher", "gpboost_cc"] 
replicate: 10
n_groups: [100] # [200,  1000]
group_size: [10, 100, 500] # , 1000] #[100, 1000, 2000] #, 1000]
likelihood:  ["ald", "gaussian"]  #, "ald"] #, "gaussian"]
randeff: "Two_completely_crossed_random_effects" #"Two_completely_crossed_random_effects" #"One_random_effect"
estimate_hyper: True

delta_logl: 0.1
alpha: 0.9
target_quantile: 0.95
gpb_approxs: {"gpboost_fisher": "asymmetric_laplace",
            "gpboost_fisher_twostage": "asymmetric_laplace", 
            "gpboost_fisher_f": "asymmetric_laplace_fisher_mode_finding",
            "gpboost_fisher_fc": "asymmetric_laplace_fisher_mode_finding_continue",
            "gpboost_lls": "asymmetric_laplace_lls_laplace",
            "gpboost_lls_f": "asymmetric_laplace_lls_laplace_fisher_mode_finding",
            "gpboost_lls_fc": "asymmetric_laplace_lls_laplace_fisher_mode_finding_continue",
            "gpboost_cc": "asymmetric_laplace_constant_curvature_fisher_mode_finding_continue",
            "gpboost_cc_groups": "asymmetric_laplace_constant_curvature_groups_fisher_mode_finding",
            "gpboost_lls_groups": "asymmetric_laplace_lls_laplace_groups_fisher_mode_finding",
            "gpboost_cc_f": "asymmetric_laplace_constant_curvature_fisher_mode_finding",
            "gpboost_cc_fc": "asymmetric_laplace_constant_curvature_fisher_mode_finding_continue",
            "gpboost_cc_freq": "asymmetric_laplace_constant_curvature_var_cor_pred_freq_asym",
            "gpboost_normal": "gaussian",
            "gpboost_lls_v2": "asymmetric_laplace_lls_laplace_v2",
            "gpboost_lls_v2_f": "asymmetric_laplace_lls_laplace_v2_fisher_mode_finding",
            "gpboost_lls_v2_fc": "asymmetric_laplace_lls_laplace_v2_fisher_mode_finding_continue",
            "gpboost_lls_freq" : "asymmetric_laplace_lls_laplace_var_cor_pred_freq_asym",
            "gpboost_lls_v2_freq": "asymmetric_laplace_lls_laplace_v2_var_cor_pred_freq_asym",
            "gpboost_lls_v2_groups": "asymmetric_laplace_lls_laplace_groups_fisher_mode_finding" }


##### for the analysis of the results ######
all_models : ["gpboost_cc", "gpboost_fisher", "bayesqr", "brms"]  #lqmm
models_with_hyperparams: ["gpboost_cc", "gpboost_fisher", "brms", "lqmm"] #, "lqmm"] 

            
name_dict : {"gpboost_lls": "LLS", "gpboost_cc": "TKC", "gpboost_cc_freq": "TKC-SW",
           "brms": "BRMS", "lqmm":"LQMM", "gpboost_normal": "gpbN", "gpboost_fisher": "Fisher", 
           "gpboost_lls_v2": "LLSV2", "gpboost_lls_freq": "LLSsand",
           "gpboost_cc_f":"CCf","gpboost_cc_fc":"CCfc","gpboost_lls_f":"LLSf",
           "gpboost_lls_fc":"LLSfc","gpboost_fisher_f":"Fisherf","gpboost_fisher_fc":"Fisherfc",
           "gpboost_lls_v2_f":"LLSV2f","gpboost_lls_v2_fc":"LLSV2fc", "gpboost_lls_groups": "LLSG", "gpboost_lls_v2_groups": "LLS2G",
           "bayesqr": "BayesQR",  "gpboost_fisher_twostage": "F2stage"}
           
likelihood_dict : {"gaussian":"N", "ald": "ALD", "t":"t", "chi":"chi", "ald_heteroscedastic": "HetALD"}
